// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KongaTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void wrongUsernamePassword() {
    // Test name: WrongUsername/Password
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x704 | 
    driver.manage().window().setSize(new Dimension(1296, 704));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | type | id=username | ugolam2525@yahoo.co.uk
    driver.findElement(By.id("username")).sendKeys("ugolam2525@yahoo.co.uk");
    // 5 | type | id=password | ogugua28
    driver.findElement(By.id("password")).sendKeys("ogugua28");
    // 6 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 7 | type | id=password | ogugua
    driver.findElement(By.id("password")).sendKeys("ogugua");
    // 8 | click | css=.\_988cf_1aDdJ | 
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    // 9 | mouseOver | css=.\_988cf_1aDdJ | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_988cf_1aDdJ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseOut | css=.\_988cf_1aDdJ | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 11 | click | css=.\_71d30_2oCCX | 
    driver.findElement(By.cssSelector(".\\_71d30_2oCCX")).click();
    // 12 | verifyText | css=.\_9a1ab_k0UMi:nth-child(3) | The username or password you have entered is incorrect. Please try again.
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).getText(), is("The username or password you have entered is incorrect. Please try again."));
    // 13 | mouseOver | css=.\_40e43_1f83p > span | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_40e43_1f83p > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | click | css=.\_40e43_1f83p > span | 
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > span")).click();
    // 15 | mouseOut | css=.\_40e43_1f83p > span | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 16 | close |  | 
    driver.close();
  }
  @Test
  public void passwordlessthan6characters() {
    // Test name: Password_less_than_6_characters
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x704 | 
    driver.manage().window().setSize(new Dimension(1296, 704));
    // 3 | mouseDown | css=.\_41783_2ijjb:nth-child(6) > picture | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_41783_2ijjb:nth-child(6) > picture"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 4 | mouseUp | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 5 | click | css=nav:nth-child(1) | 
    driver.findElement(By.cssSelector("nav:nth-child(1)")).click();
    // 6 | mouseOver | linkText=FAQs | 
    {
      WebElement element = driver.findElement(By.linkText("FAQs"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | linkText=FAQs | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | mouseOver | linkText=Contact Us | 
    {
      WebElement element = driver.findElement(By.linkText("Contact Us"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | mouseOut | linkText=Contact Us | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 11 | type | id=username | ugolam2525@yahoo.co.uk
    driver.findElement(By.id("username")).sendKeys("ugolam2525@yahoo.co.uk");
    // 12 | type | id=password | ogugua28
    driver.findElement(By.id("password")).sendKeys("ogugua28");
    // 13 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 14 | type | id=password | ogug
    driver.findElement(By.id("password")).sendKeys("ogug");
    // 15 | click | css=.\_988cf_1aDdJ | 
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    // 16 | mouseOver | css=.\_988cf_1aDdJ | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_988cf_1aDdJ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 17 | mouseOut | css=.\_988cf_1aDdJ | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 18 | click | css=.\_71d30_2oCCX | 
    driver.findElement(By.cssSelector(".\\_71d30_2oCCX")).click();
    // 19 | verifyText | css=.\_9a1ab_k0UMi:nth-child(4) | The password must be at least 6 characters
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(4)")).getText(), is("The password must be at least 6 characters"));
    // 20 | click | css=.\_40e43_1f83p > span | 
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > span")).click();
    // 21 | mouseOver | css=div > a > picture > .lazyloaded | 
    {
      WebElement element = driver.findElement(By.cssSelector("div > a > picture > .lazyloaded"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 22 | mouseOut | css=div > a > picture > .lazyloaded | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 23 | close |  | 
    driver.close();
  }
}
